"""
game_plugins.py — a minimal GamePlugins feature for OpenMW.

Registering this feature (plus loadOrderMechanism()==PLUGINS_TXT on the game)
is what makes the Plugins tab appear for OpenMW: a persistent, drag-reorderable
load order the user can also sort with the companion "Sort with LOOT" tool.

It is the source of truth for the load order. The order is persisted in the
standard Mod Organizer format — two profile files, one plugin per line:

    <profile>/loadorder.txt   every plugin, in priority order
    <profile>/plugins.txt     the active plugins only

The game's onAboutToRun hook (game_openmw.py) then transcribes the active order
into openmw.cfg's content= lines at launch. Unlike the Gamebryo games we do NOT
map these files into the game's data directory: OpenMW reads openmw.cfg, never
plugins.txt, so there is nothing to map.

Modelled on oblivion_remaster/game_plugins.py but stripped of the Bethesda
master/light/medium/blueprint flag handling — OpenMW treats every plugin the
same for ordering purposes (libloot ignores the .esm/.esp master flag).
"""

from functools import cmp_to_key
from typing import Sequence

from PyQt6.QtCore import (
    QDateTime,
    QFile,
    QFileInfo,
    QStringConverter,
    QStringEncoder,
    qCritical,
    qWarning,
)

import mobase


class OpenMWGamePlugins(mobase.GamePlugins):
    def __init__(self, organizer: mobase.IOrganizer):
        super().__init__()
        self._last_read = QDateTime().currentDateTime()
        self._organizer = organizer

    def writePluginLists(self, plugin_list: mobase.IPluginList) -> None:
        if not self._last_read.isValid():
            return
        self.writeList(
            plugin_list,
            self._organizer.profile().absolutePath() + "/plugins.txt",
            False,
        )
        self.writeList(
            plugin_list,
            self._organizer.profile().absolutePath() + "/loadorder.txt",
            True,
        )
        self._last_read = QDateTime.currentDateTime()

    def readPluginLists(self, plugin_list: mobase.IPluginList) -> None:
        load_order_path = self._organizer.profile().absolutePath() + "/loadorder.txt"
        load_order = self.readLoadOrderList(plugin_list, load_order_path)
        plugin_list.setLoadOrder(load_order)
        self.readPluginList(plugin_list)
        self._last_read = QDateTime.currentDateTime()

    def getLoadOrder(self) -> Sequence[str]:
        load_order_path = self._organizer.profile().absolutePath() + "/loadorder.txt"
        plugins_path = self._organizer.profile().absolutePath() + "/plugins.txt"

        load_order_is_new = (
            not self._last_read.isValid()
            or not QFileInfo(load_order_path).exists()
            or QFileInfo(load_order_path).lastModified() > self._last_read
        )
        plugins_is_new = (
            not self._last_read.isValid()
            or QFileInfo(plugins_path).lastModified() > self._last_read
        )

        if load_order_is_new or not plugins_is_new:
            return self.readLoadOrderList(self._organizer.pluginList(), load_order_path)
        else:
            return self.readPluginList(self._organizer.pluginList())

    def writeList(
        self, plugin_list: mobase.IPluginList, file_path: str, load_order: bool
    ) -> None:
        encoder = QStringEncoder(QStringConverter.Encoding.Utf8)
        plugins_text = "# This file was automatically generated by Mod Organizer.\n"
        invalid_filenames = False
        written_count = 0
        plugins = plugin_list.pluginNames()
        plugins_sorted = sorted(
            plugins,
            key=cmp_to_key(
                lambda lhs, rhs: plugin_list.priority(lhs) - plugin_list.priority(rhs)
            ),
        )
        for plugin_name in plugins_sorted:
            if (
                load_order
                or plugin_list.state(plugin_name) == mobase.PluginState.ACTIVE
            ):
                result = encoder.encode(plugin_name)
                if encoder.hasError():
                    invalid_filenames = True
                    qCritical("invalid plugin name %s" % plugin_name)
                plugins_text += result.data().decode() + "\n"
                written_count += 1

        if invalid_filenames:
            qCritical(
                "Some plugins have invalid names and can not be loaded by the game. "
                "See mo_interface.log for the affected plugins."
            )

        if written_count == 0:
            qWarning(
                "plugin list would be empty, this is almost certainly wrong. Not saving."
            )
            return
        with open(file_path, "w", encoding="utf-8") as plugins_file:
            plugins_file.write(plugins_text)

    def readLoadOrderList(
        self, plugin_list: mobase.IPluginList, file_path: str
    ) -> list[str]:
        plugin_names = [
            plugin for plugin in self._organizer.managedGame().primaryPlugins()
        ]
        plugin_lookup: set[str] = set(name.lower() for name in plugin_names)

        try:
            with open(file_path, encoding="utf-8") as file:
                for line in file:
                    if line.startswith("#"):
                        continue
                    plugin_file = line.rstrip("\n").rstrip("\r")
                    if not plugin_file:
                        continue
                    if plugin_file.lower() not in plugin_lookup:
                        plugin_lookup.add(plugin_file.lower())
                        plugin_names.append(plugin_file)
        except FileNotFoundError:
            return self.readPluginList(plugin_list)

        return plugin_names

    def readPluginList(self, plugin_list: mobase.IPluginList) -> list[str]:
        plugins = [plugin for plugin in plugin_list.pluginNames()]
        sorted_plugins: list[str] = []
        primary = [plugin for plugin in self._organizer.managedGame().primaryPlugins()]
        primary_lower = [plugin.lower() for plugin in primary]
        for plugin_name in primary:
            if plugin_list.state(plugin_name) != mobase.PluginState.MISSING:
                plugin_list.setState(plugin_name, mobase.PluginState.ACTIVE)
            sorted_plugins.append(plugin_name)
        plugin_remove = [plugin for plugin in plugins if plugin.lower() in primary_lower]
        for plugin in plugin_remove:
            plugins.remove(plugin)

        plugins_txt_exists = True
        file_path = self._organizer.profile().absolutePath() + "/plugins.txt"
        file = QFile(file_path)
        if not file.open(QFile.OpenModeFlag.ReadOnly):
            plugins_txt_exists = False
        if file.size() == 0:
            plugins_txt_exists = False
        if plugins_txt_exists:
            while not file.atEnd():
                line = file.readLine()
                if line.size() > 0 and line.at(0).decode() != "#":
                    name = line.trimmed().data().decode()
                    if name and name.lower() in [p.lower() for p in plugins]:
                        plugin_list.setState(name, mobase.PluginState.ACTIVE)
                        sorted_plugins.append(name)
                        plugins.remove(name)
            file.close()

        # Default state for plugins not listed in plugins.txt:
        #  - fresh profile (no/empty plugins.txt): activate everything, mirroring
        #    OpenMW's own launcher which enables all discovered content files. This
        #    is what makes the Plugins tab show the user's mods as checked on first
        #    open instead of an all-unchecked list.
        #  - existing plugins.txt: a plugin absent from it was deliberately left
        #    out, so keep it inactive.
        default_state = (
            mobase.PluginState.INACTIVE
            if plugins_txt_exists
            else mobase.PluginState.ACTIVE
        )
        for plugin_name in plugins:
            plugin_list.setState(plugin_name, default_state)

        return sorted_plugins + plugins

    def lightPluginsAreSupported(self) -> bool:
        return False

    def mediumPluginsAreSupported(self) -> bool:
        return False

    def blueprintPluginsAreSupported(self) -> bool:
        return False
